language: python
python:
  - 3.5
  - 3.6
env:
  - INSTALL_EXTRAS=[VISA,plotting,tektronix,zurich-instruments]
  - INSTALL_EXTRAS=[VISA,plotting,tektronix,zurich-instruments,Faster-fractions]

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: INSTALL_EXTRAS=[VISA,plotting,tektronix,zurich-instruments]
    - python: 3.7
      dist: xenial
      sudo: true
      env: INSTALL_EXTRAS=[VISA,plotting,tektronix,zurich-instruments,Faster-fractions]

#use container based infrastructure
sudo: false

#these directories are persistent
cache: pip

# install dependencies for gmpy2
addons:
  apt:
    update: true

    sources:
      # newer compiler for zhinst
      - ubuntu-toolchain-r-test

    packages:
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - gcc-8
      - g++-8

before_install:
  - eval "CC=gcc-8 && GXX=g++-8"
  - pip install coverage coveralls
install:
  - pip install .$INSTALL_EXTRAS
script:
  - "coverage run --source=qupulse --rcfile=coverage.ini setup.py test"
after_success:
  - coveralls

notifications:
  email: false
